name: Gradle release
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - gradle.properties
      - .github/.release-please-manifest.json
      - .github/renovate.json

jobs:
  call-release:
    uses: GrassMC/.github/.github/workflows/shared-gradle-release.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

    with:
      artifacts-path: plugin/build/libs
